server:
  port: 8085

spring:
  application:
    name: EXTERNALISE-MS
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Amiyakumarmishra/ConfigService-HotelRatingApp
          clone-on-start: true
          default-label: main